Default: &defaults
  database: data-analyze.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: data-analyze_test.sqlite3
  <<: *defaults

Staging:
  database: data-analyze_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: data-analyze_production.sqlite3
  poolsize: 100
  <<: *defaults
